### ISSUE TITLE
Error running fe2

### ISSUE THREAD

**Issue by firetix** [fastai/fastec2#5] opened 2019-02-25 06:10 UTC
After Installing the fastec2 the normal way: 
`pip install git+https://github.com/fastai/fastec2.git` 
I get the following error to reproduce run :`fe2 region Ohio`
You should be getting 
`Traceback (most recent call last):
  File "/Users/mo/.pyenv/versions/3.6.4/bin/fe2", line 11, in <module>
    load_entry_point('fastec2==1.0.0', 'console_scripts', 'fe2')()
  File "/Users/mo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/Users/mo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/Users/mo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/fastec2/__init__.py", line 4, in <module>
    from .ec2 import *
  File "/Users/mo/.pyenv/versions/3.6.4/lib/python3.6/site-packages/fastec2/ec2.py", line 10, in <module>
    from .scripts import *
ModuleNotFoundError: No module named 'fastec2.scripts'`

My python version is `Python 2.7.10`

**Comment by aglavers** [comment] 2019-03-11 21:26
Possible duplicate of https://github.com/fastai/fastec2/issues/6 because of 
` line 10, in <module> from .scripts import * ModuleNotFoundError: No module named 'fastec2.scripts'`

**Closed as completed** 2019-03-19 21:48 UTC
